### ISSUE TITLE
Bug: As an IATI Published, I am unable to validate the IATI XML ater the upload

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#77] opened 2020-02-20 07:34 UTC
After successfully generating an XML and uploading it to IATI Validator, clicking on Validation button directs me to a page where Report Status = "File uploaded (step 1 of 3)". This ticket doesn't allow attaching media files. Please let me know on my email id, if I should share an image of the browser.,Reporter,: BRINDA SAPRA,E-mail,: ,bsapra@verasolutions.org

Location,: ,https://test-validator.iatistandard.org/,Referrer,: ,https://iatistandard.org/en/news/new-iati-validator-launched-for-public-testing/,User-Agent,: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36,Screen Resolution,: 1280 x 720
submitted via feedback button
USER-32

**Comment by PetyaKangalova** [comment] 2020-02-20 10:47
I have responded to the user directly via email and will follow-up here with more detail on what the issue is, and if there is an existing bug.

**Comment by PetyaKangalova** [comment] 2020-02-21 10:08
Linking to [Discuss post](https://discuss.iatistandard.org/t/new-iati-validator-launched-for-public-testing/1870/5) with link to the error the user is receiving. I have asked if I can also test uploading their file to verify the error.  @rolfkleef , if you can already identify if there is a bug, please check and respond here. Thanks !

**Comment by PetyaKangalova** [comment] 2020-02-21 10:19
@rolfkleef  I tested with their file and get the same error, so labeling as a bug.

**Comment by Mhirji** [comment] 2020-02-21 13:49
@rolfkleef , I am seeing this also, but only on the org file.  activity files seem ok.  my personal link is https://stage.dataworkbench.io/iati-feedback/validate/71b63d26-b4d0-435f-a524-65755aa71240 if it is helpful.  Also, browser debug window is not showing any errors, only log, just a polling console log.  let me know if you need more info :)

**Comment by Mhirji** [comment] 2020-02-21 13:52
just tried again and this time it went through . . . personal url https://stage.dataworkbench.io/validate/407e6330-9e2e-4303-9a31-98ebfbf2cb66.  same file, just different timing.

**Comment by PetyaKangalova** [comment] 2020-02-28 13:33
@rolfkleef I copied you in my response to Brinda. As they are currently working on a timeframe to publish, could you update us on estimates or if there is a way to run the file through the validator so that identified error can be fixed. Thanks !

**Comment by rolfkleef** [comment] 2020-03-03 22:33
Thanks, there were several schema validation issues that were not properly caught when applying the rules (done after schema validation). It should provide a report now (you'll have to upload the file again as the previous version has been removed by now).

**Comment by PetyaKangalova** [comment] 2020-03-05 10:16
@rolfkleef  thanks, I checked the file can now successfully go through he validator: https://test-validator.iatistandard.org/view/dqf/files/4da299b5-6c47-41d3-b4e8-9b51b957ba84?isTestfiles=true

I'll wait for the user to confirm as well and then close this issue.

**Comment by PetyaKangalova** [comment] 2020-04-07 09:53
User confirmed issue has been fixed so closing.

**Closed by PetyaKangalova** 2020-04-07 09:53 UTC
Labels: bug
